### ISSUE TITLE
Use of old-style format leads to advice with broken link

### ISSUE THREAD

**Issue by richiemorrisroe** [Instagram/Fixit#115]
Hey,

Thanks for the tool. 

There appears to be an invalid link in (at least) one of the advices.

Note the attached file. 

When running `python -m fixit.cli.run_rules ` with a file with the following contents:
```
myname = "richie"
string_old = "This is {name}'s string".format(name=myname)

string_new = f"This is {myname}'s string"
```

I get the following advice:

> invalid_link_suggestion.py:2:14
>    UseFstringRule: Do not use printf style formatting or .format(). Use f-string instead to be more readable and
>   efficient. See https://fburl.com/usefstring.```

I mean, I like fburls, I remember them well. However, I (and pretty much every non-FB employee) have no access to them. 

It would probably be better if this pointed to a link accessible from the public web.

**Comment by jimmylai** [comment]
Nice catch! We should not use fburl here.

Ideally, we can have the link automatically generated by Fixit core as `f"https://fixit.readthedocs.io/en/latest/{rule_name}.html"` and append to the message at runtime.

**Comment by acharles7** [comment]
[https://www.python.org/dev/peps/pep-0498/](https://www.python.org/dev/peps/pep-0498/)

**Comment by jimmylai** [comment]
@acharles7 , the PEP provides f-string usage examples and looks good as a replacement to the existing link. Feel free to submit a PR!

**Comment by acharles7** [comment]
Thanks, will make PR soon.
