### ISSUE TITLE
Script to add new rules

### ISSUE THREAD

**Issue by acharles7** [Instagram/Fixit#119]
I think it would be a great idea to add a script to generate a higher-level skeleton of adding a new rule in [fixit/rules](https://github.com/Instagram/Fixit/tree/master/fixit/rules)
The possible skeleton would be
```python 

# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import libcst as cst

from fixit import CstLintRule, InvalidTestCase as Invalid, ValidTestCase as Valid

class NewRule(CstLintRule):
    '''
    docstring or new_rule information
    '''
    MESSAGE = 'message'
    VALID = [Valid()]
    INVALID = [Invalid()]
```

Right now, I have only added license, imports, and class. But, we can add other things too if needed in future.
if we generate this skeleton using python scripts then It will be very easy for other contributors to add new rules.

So, to add new rule, run `add_new_rule.py` file (will be located in fixit/scripts) using
`python -m fixit.scripts.add_new_rule --name rule_name`
This will add new_rule.py in [fixit/rules](https://github.com/Instagram/Fixit/tree/master/fixit/rules)

Please let me know what you think.
I am happy to make PR for this script in fixit package.

**Comment by jimmylai** [comment]
This is an awesome idea. Internally, we have this as a VSCode plugin, so it automatically add the skeleton when creating a new file in rules.

Your template file looks good.

All our current commands are in `fixit.cli`.
So `python -m fixit.cli.add_new_rule` fits better.
https://github.com/Instagram/Fixit/tree/master/fixit/cli

Other than just create the new file in fixit/rules, the user may want to add their custom rule in their repository, so maybe allow providing a path of the new file to be more flexible.
E.g. `python -m fixit.cli.add_new_rule --path fixit/fules/new_rule.py`

You're more than welcome to submit a PR!

**Comment by acharles7** [comment]
I think If we create and place a `new_rule.py` file in fixit/rules then it would be redundant and we have to mention this in the documentation.

**Comment by acharles7** [comment]
I am working on it and let you know. In the meantime, you can assign this to me.
I'll use `python -m fixit.cli.add_new_rule --name rule_name --path fixit/rules`
this will add and place `rule_name.py` at path argument value
Sounds good?

**Comment by jimmylai** [comment]
Yes, the name and path could be redundant. My suggestions is to only use the `path` parameter to provide the new rule file name to keep it simple. (remove the name.)
`python -m fixit.cli.add_new_rule --path fixit/fules/new_rule.py`
