### ISSUE TITLE
"Edit on GitHub" links are broken

### ISSUE THREAD

**Issue by kappa** [Instagram/Fixit#134]
Readthedocs-hosted doc pages for individual rules all have links at the top right corner that are broken.

Example: https://fixit.readthedocs.io/en/latest/rules/NoAssertEqualsRule.html has a link to https://github.com/Instagram/Fixit/blob/master/docs/source/rules/NoAssertEqualsRule.rst which does not exist.

**Comment by iamdevvalecha** [comment]
@kappa these are using absolute links not relative links. Does not work.

**Comment by iamdevvalecha** [comment]
i wanna work on this issue
