### ISSUE TITLE
Error in Readme of the description of setting up virtualenv

### ISSUE THREAD

**Issue by lukuang** [Instagram/Fixit#139]
As stated in the title, there is an error in the Readme in the setting up vr here:
`pip install -r requirements.txt -r requirements-dev.txt`

In one of the commands above, there is a command `cd fixit`. Because of this, the paths of the requirement files are incorrect. The above command should be:
`pip install -r ../requirements.txt -r ../requirements-dev.txt`

**Comment by jimmylai** [comment]
In the README, it clones Fixit as `fixit` and then do `cd fixit`.
`requirements.txt` and `requirements-dev.txt` are at the top level of cloned `fixit`. No `../` is needed.
