### ISSUE TITLE
Fixit CLI 

### ISSUE THREAD

**Issue by acharles7** [Instagram/Fixit#147]
Launch a brand new `fixit-cli` using `argparse` (Will fix  #124) 

Currently, all the scripts in `fixit/cli` are individual, which is good as per my plan of new CLI.

Here's my plan of implementing this:
The CLI will look like the following:

`setup.py`

```python
entry_points={
        'console_scripts': [
            'fixit-cli = cli.main:launch_cli'
        ],
    },
```

`fixit/cli/main.py`

```python
from fixit.cli import apply_fix

def _parse_flags(argv: List[str]) -> argparse.Namespace:
    parser = argparse_flags.ArgumentParser(prog="fixit", description="Fixit CLI ")
    # Register sub-commands
    subparser = parser.add_subparsers(title='command')

    # Will add all individual scripts i.e.
    add_new_rule.register_subparser(subparser) # add_new_rule
    apply_fix.register_subparser(subparser) # apply_fix
    ...
    return parser.parse_args(argv[1:])

def main(args: argparse.Namespace) -> None:
    args.subparser_fn(args)

def launch_cli() -> None:
    app.run(main, flags_parser=_parse_flags)

if __name__ == "__main__":
    launch_cli()
```

`fixit/cli/apply_fix.py`

```python
def register_subparser(parsers: argparse._SubParsersAction) -> None:
    """Add subparser for `apply_fix` command."""
    apply_fix_parser = parsers.add_parser(
        "apply_fix",
        help=APPLY_FIX_HELP_TEXT,
        parents=[get_paths_parser(), ...]
    )

    apply_fix_parser.set_defaults(subparser_fn=_apply_fixes)


def _apply_fixes(args: argparse.Namespace):
    # to-do
```

By doing this we can use fixit as a console script, which is very convenient.

I am planning to do this in small and individual PRs, starting from `fixit/cli/main.py` then each sub-commands (`apply_fix, add_new_rule`), etc.
Other files will stay as it is(`utils.py, args.py`).

Let me know if you want to add anything or have any suggestions on this. So, I can start ASAP

*Note: we can change CLI name later on or suggest the best name that suits well for this*

@jimmylai

**Comment by jimmylai** [comment]
Having a single CLI command is a good idea. We already do that for LibCST.
To keep it simple, the command should be named as `fixit`
and users can provide different sub-command, e.g.
- fixit run_rules
- fixit apply_fix

Why do you need both `launch_cli` and `main` rather than just a `main`?
Then the console-script can point to `cli.main:main`.

**Comment by jimmylai** [comment]
Your PRs are very welcome!

**Comment by acharles7** [comment]
> Your PRs are very welcome!

Thank you, Should I do in separate folder? i.e `fixit/cli2/`

**Comment by acharles7** [comment]
> Having a single CLI command is a good idea. We already do that for LibCST.
> To keep it simple, the command should be named as `fixit`
> and users can provide different sub-command, e.g.
> 
> * fixit run_rules
> * fixit apply_fix
> 
> Why do you need both `launch_cli` and `main` rather than just a `main`?
> Then the console-script can point to `cli.main:main`.

Yes, I can do that too. But, I want to parse arguments separately and TBH more modular. So this is one way I can think of.
Let me know if you have any other ideas.

**Comment by acharles7** [comment]
> > Your PRs are very welcome!
> 
> Thank you, Should I do in separate folder? i.e `fixit/cli2/`

How should I make PRs? because I need to change some existing files in each small PR for each sub-command, which might cause conflict.

**Comment by jimmylai** [comment]
> > > Your PRs are very welcome!
> > 
> > 
> > Thank you, Should I do in separate folder? i.e `fixit/cli2/`
> 
> How should I make PRs? because I need to change some existing files in each small PR for each sub-command, which might cause conflict.

I would just add a `cli/main.py` and modify other files to add them to the new CLI while keeping their existing CLI works for backward compatibility.
One or multiple PRs are both fine to me.

**Comment by acharles7** [comment]
Thank you.
