### ISSUE TITLE
Update imports with autofix

### ISSUE THREAD

**Issue by ljodal** [Instagram/Fixit#170]
Hi, I'm looking into creating a rule telling users not to use a certain base class, but rather use a different one. Providing an autofix for this would require changing an import, which I can't figure out how to do. Is this currently possible?

For example I'd like to replace this:

```python
from a import A

class MyClass(A):
    pass
```

with this:

```python
from b import B

class MyClass(B):
    pass
```

I see that the `NoNamedTupleRule` leaves old imports in place and does not add an import for `dataclasses`, so I'm half assuming this isn't possible at the moment. Any plans to add support for this? Let me know if there's anything I can do to help :)

**Comment by jmhodges-color** [comment]
Would love to hear if there's a story for this! I could totally guess that I missed something obvious in the API, but AddImportsVisitor in libcst is so handy and doesn't have a trivial mapping, it seems.

**Comment by zsol** [comment]
I don't think this is possible at the moment, but agreed would be very useful. Unfortunately this feature would require rethinking how the replacement API works (currently you can only declare autofixes in the node you're visiting). Or at least adding a special case for imports. @amyreese what do you think?

**Comment by amyreese** [comment]
I believe this should be possible in the upcoming 2.0 release, but would require a separate call to `self.report(…)` and providing a separate target node and replacement. I opened #356 to track the more general idea of offering multiple replacements in a single report.
