### ISSUE TITLE
Docs to describe updating the docs

### ISSUE THREAD

**Issue by lisroach** [Instagram/Fixit#185]
I found myself unsure of how to update the docs other than regenerating them with `tox -e docs`

We should update the README to explain the steps:
1. activate the venv
2. Run `jupyter notebook`
3. This will launch a browser window where you can edit the docs directly
4. Use "save and checkpoint" -> I think?
5. Regenerate the docs with `tox -e docs`

**Comment by srisatya1197** [comment]
@lisroach will try to work on this.

**Comment by jack1142** [comment]
I suggest also mentioning that one should use "Cell -> All Output -> Clear" option before committing (or [setting up a pre save hook](https://jupyter-notebook.readthedocs.io/en/stable/extending/savehooks.html#examples)):
![image](https://user-images.githubusercontent.com/6032823/178157556-5dc82f24-b336-4295-b7a5-95db3769f94f.png)

**Comment by amyreese** [comment]
We are dropping the notebook-based docs.
