### ISSUE TITLE
Pre-commit hook configuration

### ISSUE THREAD

**Issue by Jackenmen** [Instagram/Fixit#193]
It would be awesome to get out-of-the-box support for [pre-commit](https://pre-commit.com/) as plenty of other linters and auto-formatters such as flake8, pylint, black, or isort provide.

This is a matter of creating an appropriate `.pre-commit-hooks.yaml` file in the root of the repository as shown here: https://pre-commit.com/#new-hooks

**Comment by flying-sheep** [comment]
I’m very surprised this project has none!

**Comment by zsol** [comment]
We'd love to take PRs 🙃

**Comment by amyreese** [comment]
I will make this happen once we have the new API and CLI nailed down.
