### ISSUE TITLE
Is there any list of fixers provided by Fixit?

### ISSUE THREAD

**Issue by Zac-HD** [Instagram/Fixit#194]
[I'd like to run them from `shed --refactor`](https://github.com/Zac-HD/shed/issues/7), but I can't find any documentation or even CLI help stating what rules have autofixers, or what the fixers do.  #90 is the closest I know of.

**Comment by jimmylai** [comment]
@Zac-HD The list of rules and autofixer info can be found on the document. It also provide autofix examples for invalid code.
https://fixit.readthedocs.io/en/latest/rules/AddMissingHeaderRule.html

**Comment by Zac-HD** [comment]
Thanks Jimmy!
