### ISSUE TITLE
Incompatible with flake8 5.0

### ISSUE THREAD

**Issue by zsol** [Instagram/Fixit#222]
```
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/fixit/common/flake8_compat.py", line 135, in reset
    arguments=self.args,
AttributeError: 'Flake8CompatApplication' object has no attribute 'args'
```

That attribute was removed in https://github.com/PyCQA/flake8/commit/8d3afe40e1e8ba70418bada82608d47e61eedb8f which got released in 5.0.0

**Comment by thatch** [comment]
fixit itself should probably also add a max constraint: https://github.com/Instagram/Fixit/blob/main/requirements.txt
