### ISSUE TITLE
no_assert_equals is incomplete

### ISSUE THREAD

**Issue by cricalix** [Instagram/Fixit#313]
The rule `no_assert_equals` is incomplete; it only checks for `assertEquals`. There are probably 7 cases that the linter could fix, according to the Python 3 docs.

I'm happy to produce a PR for this, but before I do (and have to do it a different way):
* One rule file per deprecated alias, with one match and replace per file?
* One rule file for all deprecated aliases with a loop to match and replace?

**Comment by amyreese** [comment]
I think a single rule/file that handles all deprecated aliases would be better, and result in less duplicate code and fewer visits to the syntax tree.
