### ISSUE TITLE
Conventional file path/line number separator (`:` instead of `@`)

### ISSUE THREAD

**Issue by samueljsb** [Instagram/Fixit#397]
The output when a line is reported uses the `@` character to separate the filename from the line number, e.g:

```
path/to/some/module.py@91:12 An error is at this location.
```

This differs from most other tools, which use a colon. The colon syntax is understood by many other tools that parse output (e.g. [`mypy-json-report`](https://pypi.org/project/mypy-json-report/)) and the file finder in most editors (e.g. VS Code). e.g:

```
path/to/some/module.py:91:12 An error is at this location.
```

Would the maintainers be open to changing the output format to be the same as other tools? It would (imo) make fixit output much easier to work with.

**Comment by samueljsb** [comment]
Would the maintainers be open to a PR that changes this? If there is a concern about backwards compatibility, would a `--format` option be acceptable?

**Comment by meshy** [comment]
This is related to https://github.com/Instagram/Fixit/issues/305
