### ISSUE TITLE
ChatBox _ UI _  The ChatBox UI has incorrect alignment, and the last reels were not refreshed.

### ISSUE THREAD

**Issue by Udhayanila8** [Instagram/Fixit#471]
### **Application**
Instagram application

**### Version**
338.0.0.31.95

### **Screens**
ChatBox and reels

### **Steps to recreate**

1. Open and log in to the Instagram account.
2. Open the chat box.
3. Check the chats.
4. Open the last received reels and play.

**Note: It is occurring randomly**

### **Current behavior**
The camera icon alignment is collapsed and not in order.
When opening the last received reels, it shows previously viewed reels and auto refresh does not happen.

### **Expected behavior**
The camera alignment should be in order.
When choosing the last received reels, it should display only the selected reels.

### **Screenshots for reference**
![image](https://github.com/Instagram/Fixit/assets/82999693/c8c9d340-6ca8-485a-9a43-fc8bd5cde067)

**### Screen recording for reel issue**
**Last viewed reels**

https://github.com/Instagram/Fixit/assets/82999693/00db8d4a-e265-4e56-a964-6d144142dc1c

**Opening the new reels but it shows the previously opened reels, close and reopen only it is showing the correct one.**

https://github.com/Instagram/Fixit/assets/82999693/add20b93-d02d-489c-8953-1e9f31249866

**Comment by fried** [comment]
This project is unrelated to the Instagram app, please don't raise issues about it here.
